### ISSUE TITLE
Alte Aufgabenlösung verwenden wird ignoriert

### ISSUE THREAD

**Issue by pascalseeland** [leifos-gmbh/ViPLab#19]
Bei Fortsetzen eines Tests wird die alte Lösung nicht als Ausgang verwendet, selbst wenn das gewünscht wird.

**Comment by Legion2** [comment]
So wie ich das sehe wird immer die vorherige Lösung genommen, auch wenn das nicht wünscht ist.

**Comment by Legion2** [comment]
Beim Fortsetzen wird da weiter gemacht wo man aufgehört hat.
Wenn man den Test startet und ihn schon mal abgeschlossen hatte und ausgewählt hat, damit man die Lösung des vorher abgeschlossenen Testdurchlaufes jetzt verwenden möchte, wird dies aktuell nicht gemacht.
